export interface CountryEntry {
  name: string;
  iso: string;
  tier: 1 | 2 | 3 | 4 | 5;
}

export const MASTER_COUNTRIES: CountryEntry[] = [
  // Tier 1 - Beginner (20)
  { name: 'United States', iso: 'us', tier: 1 },
  { name: 'United Kingdom', iso: 'gb', tier: 1 },
  { name: 'France', iso: 'fr', tier: 1 },
  { name: 'Japan', iso: 'jp', tier: 1 },
  { name: 'Brazil', iso: 'br', tier: 1 },
  { name: 'Germany', iso: 'de', tier: 1 },
  { name: 'Canada', iso: 'ca', tier: 1 },
  { name: 'Italy', iso: 'it', tier: 1 },
  { name: 'China', iso: 'cn', tier: 1 },
  { name: 'India', iso: 'in', tier: 1 },
  { name: 'Australia', iso: 'au', tier: 1 },
  { name: 'Mexico', iso: 'mx', tier: 1 },
  { name: 'Spain', iso: 'es', tier: 1 },
  { name: 'Russia', iso: 'ru', tier: 1 },
  { name: 'Argentina', iso: 'ar', tier: 1 },
  { name: 'South Korea', iso: 'kr', tier: 1 },
  { name: 'Netherlands', iso: 'nl', tier: 1 },
  { name: 'Sweden', iso: 'se', tier: 1 },
  { name: 'Switzerland', iso: 'ch', tier: 1 },
  { name: 'Turkey', iso: 'tr', tier: 1 },

  // Tier 2 - Easy (20)
  { name: 'Norway', iso: 'no', tier: 2 },
  { name: 'Denmark', iso: 'dk', tier: 2 },
  { name: 'Finland', iso: 'fi', tier: 2 },
  { name: 'Ireland', iso: 'ie', tier: 2 },
  { name: 'Portugal', iso: 'pt', tier: 2 },
  { name: 'Greece', iso: 'gr', tier: 2 },
  { name: 'Poland', iso: 'pl', tier: 2 },
  { name: 'Belgium', iso: 'be', tier: 2 },
  { name: 'Austria', iso: 'at', tier: 2 },
  { name: 'South Africa', iso: 'za', tier: 2 },
  { name: 'Egypt', iso: 'eg', tier: 2 },
  { name: 'Saudi Arabia', iso: 'sa', tier: 2 },
  { name: 'Israel', iso: 'il', tier: 2 },
  { name: 'Thailand', iso: 'th', tier: 2 },
  { name: 'Vietnam', iso: 'vn', tier: 2 },
  { name: 'Indonesia', iso: 'id', tier: 2 },
  { name: 'New Zealand', iso: 'nz', tier: 2 },
  { name: 'Chile', iso: 'cl', tier: 2 },
  { name: 'Colombia', iso: 'co', tier: 2 },
  { name: 'Ukraine', iso: 'ua', tier: 2 },

  // Tier 3 - Medium (20)
  { name: 'Hungary', iso: 'hu', tier: 3 },
  { name: 'Czechia', iso: 'cz', tier: 3 },
  { name: 'Romania', iso: 'ro', tier: 3 },
  { name: 'Croatia', iso: 'hr', tier: 3 },
  { name: 'Iceland', iso: 'is', tier: 3 },
  { name: 'Morocco', iso: 'ma', tier: 3 },
  { name: 'Nigeria', iso: 'ng', tier: 3 },
  { name: 'Kenya', iso: 'ke', tier: 3 },
  { name: 'Pakistan', iso: 'pk', tier: 3 },
  { name: 'Bangladesh', iso: 'bd', tier: 3 },
  { name: 'Philippines', iso: 'ph', tier: 3 },
  { name: 'Malaysia', iso: 'my', tier: 3 },
  { name: 'Singapore', iso: 'sg', tier: 3 },
  { name: 'Peru', iso: 'pe', tier: 3 },
  { name: 'Venezuela', iso: 've', tier: 3 },
  { name: 'Cuba', iso: 'cu', tier: 3 },
  { name: 'Jamaica', iso: 'jm', tier: 3 },
  { name: 'Iran', iso: 'ir', tier: 3 },
  { name: 'Iraq', iso: 'iq', tier: 3 },
  { name: 'United Arab Emirates', iso: 'ae', tier: 3 },
  { name: 'Bulgaria', iso: 'bg', tier: 3 },
  { name: 'Belarus', iso: 'by', tier: 3 },
  { name: 'Serbia', iso: 'rs', tier: 3 },
  { name: 'Cyprus', iso: 'cy', tier: 3 },
  { name: 'Costa Rica', iso: 'cr', tier: 3 },
  { name: 'Dominican Republic', iso: 'do', tier: 3 },
  { name: 'Algeria', iso: 'dz', tier: 3 },
  { name: 'Ethiopia', iso: 'et', tier: 3 },
  { name: 'Lebanon', iso: 'lb', tier: 3 },
  { name: 'Kuwait', iso: 'kw', tier: 3 },
  { name: 'North Korea', iso: 'kp', tier: 3 },
  { name: 'Myanmar', iso: 'mm', tier: 3 },
  { name: 'Panama', iso: 'pa', tier: 3 },
  { name: 'Syria', iso: 'sy', tier: 3 },
  { name: 'Taiwan', iso: 'tw', tier: 3 },
  { name: 'Luxembourg', iso: 'lu', tier: 3 },
  { name: 'Malta', iso: 'mt', tier: 3 },

  // Tier 4 - Hard (20)
  { name: 'Uzbekistan', iso: 'uz', tier: 4 },
  { name: 'Kazakhstan', iso: 'kz', tier: 4 },
  { name: 'Paraguay', iso: 'py', tier: 4 },
  { name: 'Uruguay', iso: 'uy', tier: 4 },
  { name: 'Bolivia', iso: 'bo', tier: 4 },
  { name: 'Ecuador', iso: 'ec', tier: 4 },
  { name: 'Namibia', iso: 'na', tier: 4 },
  { name: 'Latvia', iso: 'lv', tier: 4 },
  { name: 'Lithuania', iso: 'lt', tier: 4 },
  { name: 'Estonia', iso: 'ee', tier: 4 },
  { name: 'Oman', iso: 'om', tier: 4 },
  { name: 'Qatar', iso: 'qa', tier: 4 },
  { name: 'Jordan', iso: 'jo', tier: 4 },
  { name: 'Sri Lanka', iso: 'lk', tier: 4 },
  { name: 'Nepal', iso: 'np', tier: 4 },
  { name: 'Mongolia', iso: 'mn', tier: 4 },
  { name: 'Ghana', iso: 'gh', tier: 4 },
  { name: 'Tunisia', iso: 'tn', tier: 4 },
  { name: 'Slovakia', iso: 'sk', tier: 4 },
  { name: 'Slovenia', iso: 'si', tier: 4 },
  { name: 'Afghanistan', iso: 'af', tier: 4 },
  { name: 'Albania', iso: 'al', tier: 4 },
  { name: 'Armenia', iso: 'am', tier: 4 },
  { name: 'Angola', iso: 'ao', tier: 4 },
  { name: 'Azerbaijan', iso: 'az', tier: 4 },
  { name: 'Bosnia and Herzegovina', iso: 'ba', tier: 4 },
  { name: 'Bahrain', iso: 'bh', tier: 4 },
  { name: 'Botswana', iso: 'bw', tier: 4 },
  { name: 'DR Congo', iso: 'cd', tier: 4 },
  { name: 'Ivory Coast', iso: 'ci', tier: 4 },
  { name: 'Cameroon', iso: 'cm', tier: 4 },
  { name: 'Georgia', iso: 'ge', tier: 4 },
  { name: 'Guatemala', iso: 'gt', tier: 4 },
  { name: 'Honduras', iso: 'hn', tier: 4 },
  { name: 'Haiti', iso: 'ht', tier: 4 },
  { name: 'Cambodia', iso: 'kh', tier: 4 },
  { name: 'Laos', iso: 'la', tier: 4 },
  { name: 'Libya', iso: 'ly', tier: 4 },
  { name: 'Madagascar', iso: 'mg', tier: 4 },
  { name: 'North Macedonia', iso: 'mk', tier: 4 },
  { name: 'Mali', iso: 'ml', tier: 4 },
  { name: 'Montenegro', iso: 'me', tier: 4 },
  { name: 'Mozambique', iso: 'mz', tier: 4 },
  { name: 'Nicaragua', iso: 'ni', tier: 4 },
  { name: 'Papua New Guinea', iso: 'pg', tier: 4 },
  { name: 'Palestine', iso: 'ps', tier: 4 },
  { name: 'Senegal', iso: 'sn', tier: 4 },
  { name: 'Somalia', iso: 'so', tier: 4 },
  { name: 'Sudan', iso: 'sd', tier: 4 },
  { name: 'El Salvador', iso: 'sv', tier: 4 },
  { name: 'Tanzania', iso: 'tz', tier: 4 },
  { name: 'Uganda', iso: 'ug', tier: 4 },
  { name: 'Yemen', iso: 'ye', tier: 4 },
  { name: 'Zambia', iso: 'zm', tier: 4 },
  { name: 'Zimbabwe', iso: 'zw', tier: 4 },
  { name: 'Fiji', iso: 'fj', tier: 4 },
  { name: 'Trinidad and Tobago', iso: 'tt', tier: 4 },
  { name: 'Kosovo', iso: 'xk', tier: 4 },

  // Tier 5 - Expert (20)
  { name: 'Kiribati', iso: 'ki', tier: 5 },
  { name: 'Comoros', iso: 'km', tier: 5 },
  { name: 'Bhutan', iso: 'bt', tier: 5 },
  { name: 'Lesotho', iso: 'ls', tier: 5 },
  { name: 'Andorra', iso: 'ad', tier: 5 },
  { name: 'Chad', iso: 'td', tier: 5 },
  { name: 'Moldova', iso: 'md', tier: 5 },
  { name: 'Nauru', iso: 'nr', tier: 5 },
  { name: 'Palau', iso: 'pw', tier: 5 },
  { name: 'Tonga', iso: 'to', tier: 5 },
  { name: 'Vanuatu', iso: 'vu', tier: 5 },
  { name: 'Eswatini', iso: 'sz', tier: 5 },
  { name: 'Brunei', iso: 'bn', tier: 5 },
  { name: 'Turkmenistan', iso: 'tm', tier: 5 },
  { name: 'Kyrgyzstan', iso: 'kg', tier: 5 },
  { name: 'Tajikistan', iso: 'tj', tier: 5 },
  { name: 'Suriname', iso: 'sr', tier: 5 },
  { name: 'Belize', iso: 'bz', tier: 5 },
  { name: 'Bahamas', iso: 'bs', tier: 5 },
  { name: 'Cape Verde', iso: 'cv', tier: 5 },
  { name: 'Antigua and Barbuda', iso: 'ag', tier: 5 },
  { name: 'Barbados', iso: 'bb', tier: 5 },
  { name: 'Burkina Faso', iso: 'bf', tier: 5 },
  { name: 'Burundi', iso: 'bi', tier: 5 },
  { name: 'Benin', iso: 'bj', tier: 5 },
  { name: 'Central African Republic', iso: 'cf', tier: 5 },
  { name: 'Republic of the Congo', iso: 'cg', tier: 5 },
  { name: 'Djibouti', iso: 'dj', tier: 5 },
  { name: 'Dominica', iso: 'dm', tier: 5 },
  { name: 'Eritrea', iso: 'er', tier: 5 },
  { name: 'Micronesia', iso: 'fm', tier: 5 },
  { name: 'Gabon', iso: 'ga', tier: 5 },
  { name: 'Grenada', iso: 'gd', tier: 5 },
  { name: 'Gambia', iso: 'gm', tier: 5 },
  { name: 'Guinea', iso: 'gn', tier: 5 },
  { name: 'Equatorial Guinea', iso: 'gq', tier: 5 },
  { name: 'Guinea-Bissau', iso: 'gw', tier: 5 },
  { name: 'Guyana', iso: 'gy', tier: 5 },
  { name: 'Saint Kitts and Nevis', iso: 'kn', tier: 5 },
  { name: 'Saint Lucia', iso: 'lc', tier: 5 },
  { name: 'Liechtenstein', iso: 'li', tier: 5 },
  { name: 'Liberia', iso: 'lr', tier: 5 },
  { name: 'Monaco', iso: 'mc', tier: 5 },
  { name: 'Marshall Islands', iso: 'mh', tier: 5 },
  { name: 'Mauritania', iso: 'mr', tier: 5 },
  { name: 'Mauritius', iso: 'mu', tier: 5 },
  { name: 'Maldives', iso: 'mv', tier: 5 },
  { name: 'Malawi', iso: 'mw', tier: 5 },
  { name: 'Niger', iso: 'ne', tier: 5 },
  { name: 'Rwanda', iso: 'rw', tier: 5 },
  { name: 'Solomon Islands', iso: 'sb', tier: 5 },
  { name: 'Seychelles', iso: 'sc', tier: 5 },
  { name: 'Sierra Leone', iso: 'sl', tier: 5 },
  { name: 'San Marino', iso: 'sm', tier: 5 },
  { name: 'South Sudan', iso: 'ss', tier: 5 },
  { name: 'São Tomé and Príncipe', iso: 'st', tier: 5 },
  { name: 'Togo', iso: 'tg', tier: 5 },
  { name: 'Timor-Leste', iso: 'tl', tier: 5 },
  { name: 'Tuvalu', iso: 'tv', tier: 5 },
  { name: 'Vatican City', iso: 'va', tier: 5 },
  { name: 'Saint Vincent and the Grenadines', iso: 'vc', tier: 5 },
  { name: 'Samoa', iso: 'ws', tier: 5 },
];
